import os
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))

def run_chat():
    print('You: (type exit to quit)')
    
   
    system_message = """
You are The best AI out here, a You are a very helpful tutor who helps students learn about technology, computer science or any other subjects they are interested to learn about. You explain things clearly and always encourage curiosity.".

Your job is to tutor students in need.

Rules:
- Always be kind         
- Always be patient       
- Never be rude
- Never be disrespectful
- Never expect for users to quickly understand 

Response format:
- Start with a one-sentence summary of what the user said.
- Then give your response.
- End with one follow-up question.
"""
   
   
   
    history = []

    while True:
        user_input = input('>> ')

        if user_input.lower() == 'exit':
            break

        history.append({'role': 'user', 'content': user_input})

        print('History:', history)

        response = client.messages.create(
            model='claude-haiku-4-5-20251001',
            max_tokens=300,
            temperature=1,
            system=system_message,
            messages=history
        )

        reply = response.content[0].text
        print(response)
        print(f'Claude: {reply}')
        history.append({'role': 'assistant', 'content': reply})

run_chat()


#talking to chatgpt directly is different, first with chatgpt you only see thefront end whereas here you see the terminal. Chat also has its own app, their answers are better and clearer.

#lab 2:
#step 1: usage.input_tokens means it measures the text you send to the AI.
#usage.output_tokens means it measures the length of the response generated by the AI model

#step 2: max tokens to 50 made  the final answer of the chatbot much shorter.
#temp to 0 when i asked 3 times it gave identical answers
#temp to 1 it gave different answers to all
#tempereture controls if how different answers you get each time, its either the same exact answers all the time or different answers

#step 3:
#after 3 turns in the history there are 6 messages.
#the API need full history the whole time because it will forget everything you told it after you exit.


#lab 3:
#step 3: i sent messages testing different situations it stayed in role helped and answered and it also remembered messages from earlier that i had asked 
# i asked questions outside of its scope, it was stil running and even was answering my questions